# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosAssignment

pod 'SwiftyJSON'
 pod 'IQKeyboardManagerSwift'
 pod 'ReachabilitySwift', '~> 4.3.1'
 pod 'SDWebImage'
 pod 'SwiftMessages'
 pod 'SVProgressHUD'
pod 'Alamofire', '~> 4.9.1'
end
